@Service_HostAddress = https://localhost:7255

GET {{Service_HostAddress}}/

###

POST {{Service_HostAddress}}/todoitems
Content-Type: application/json
{
  "TrainerId": 1,
  "TrainerName":"Pawel",
  "TrainerLastName": "Bartkowiak",
  "TrainerPhoneNumber": "123123123"
}
###

POST {{Service_HostAddress}}/trainers/add
Content-Type: application/json
{
  "Id": 1,
  "FirstName":"Pawel",
  "LastName": "Bartkowiak",
  "PhoneNumber": "123123123"
}
###

POST {{Service_HostAddress}}/trainers/add

###

POST {{Service_HostAddress}}/users/add
Content-Type: application/json
{
  "Id": 2,
  "FirstName":"Pawel",
  "LastName": "Bartkowiak",
  "PhoneNumber": "123123123"
}
###

GET {{Service_HostAddress}}/users

###
